### ISSUE TITLE
R Package Reference

### ISSUE THREAD

**Issue by amrrs** [datails/ruigi#8]
Great Work, Thanks for the contribution.

There's an R 📦 with the same name and similar purpose as Luigi. https://github.com/kirillseva/ruigi

Just wanted to share it!

**Comment by rafarui** [comment]
> Great Work, Thanks for the contribution.
> 
> There's an R 📦 with the same name and similar purpose as Luigi. https://github.com/kirillseva/ruigi
> 
> Just wanted to share it!

yes!! thx for sharing.
